/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "outline-variant": "#e4beb7",
        "error": "#ba1a1a",
        "primary": "#b61a09",
        "surface-container": "#ffe9e5",
        "surface-tint": "#b91d0c",
        "tertiary-fixed": "#e2e0fc",
        "secondary-container": "#fe6a34",
        "on-tertiary-fixed-variant": "#45455b",
        "primary-container": "#da3621",
        "surface-container-low": "#fff0ee",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#400200",
        "error-container": "#ffdad6",
        "tertiary": "#5a5a71",
        "surface-container-highest": "#fadcd7",
        "secondary": "#ab3500",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#1a1a2e",
        "on-primary": "#ffffff",
        "on-background": "#271815",
        "inverse-on-surface": "#ffedea",
        "inverse-surface": "#3e2c29",
        "primary-fixed-dim": "#ffb4a7",
        "inverse-primary": "#ffb4a7",
        "on-tertiary": "#ffffff",
        "surface-dim": "#f1d3ce",
        "surface-container-high": "#ffe2dd",
        "primary-fixed": "#ffdad4",
        "tertiary-fixed-dim": "#c6c4df",
        "on-secondary-fixed": "#390c00",
        "on-primary-container": "#fffbff",
        "outline": "#906f6a",
        "surface": "#fff8f6",
        "background": "#fff8f6",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#910900",
        "on-secondary-container": "#5d1900",
        "tertiary-container": "#73728b",
        "on-surface": "#271815",
        "on-surface-variant": "#5b403b",
        "surface-bright": "#fff8f6",
        "surface-variant": "#fadcd7",
        "secondary-fixed": "#ffdbd0",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#ffb59d",
        "on-secondary-fixed-variant": "#832600"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "8px",
        "xl": "12px",
        "2xl": "16px",
        "full": "9999px"
      },
      "spacing": {
        "margin-desktop": "40px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "stack-xs": "4px",
        "gutter": "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "stack-xl": "48px",
        "stack-lg": "24px"
      },
      "fontFamily": {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
